services:
  company.supporthub.api:
    container_name: company.supporthub.api
    image: company.supporthub.api:dev
    build:
      context: .
      dockerfile: Source/Company.SupportHub.API/Dockerfile
