name: dotnet-dependency
on:
  pull_request:
    branches: ["main"]

jobs:
  dependency-review:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
<<<<<<< HEAD:.github/workflows/dotnet-dependency-review.yml
        os: [ubuntu-latest]
=======
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet-version: [6.0.x, 7.0.x, 8.0.x]
>>>>>>> d00fc6293f9b48e8cf010cb8ca91e6e393ef152f:.github/workflows/dependency-review.yml

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Setup .NET'
        uses: actions/setup-dotnet@v4

      - name: 'Restore Dependencies'
        run: dotnet restore

      - name: 'Run Dependency Review'
        uses: actions/dependency-review-action@v3
<<<<<<< HEAD:.github/workflows/dotnet-dependency-review.yml



=======
>>>>>>> d00fc6293f9b48e8cf010cb8ca91e6e393ef152f:.github/workflows/dependency-review.yml
